<?php

namespace App\Services\Report\Strategies;

use App\Models\User;
use App\Models\UserAttendance;
use Maatwebsite\Excel\Facades\Excel;
use App\Exports\AttendanceExport;
use App\Services\Report\Interfaces\ReportStrategy;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Illuminate\Http\Exceptions\HttpResponseException;

class AttendanceReportStrategy implements ReportStrategy
{
    /**
     * This PHP function generates an Excel report for a specific user's attendance data based on the
     * provided year and month, or returns a message indicating that the report type is under
     * construction.
     * 
     * @param array data Based on the provided code snippet, the `generate` function takes an array
     * `` as a parameter. The function first checks if a `user_id` key exists in the ``
     * array. If it does, it retrieves the user based on the `uuid`, fetches attendances for
     * 
     * @return BinaryFileResponse A BinaryFileResponse object is being returned when the  is not
     * null. This object is generated by downloading an Excel file using the AttendanceExport class and
     * the provided data. If  is null, a JSON response with a message indicating that the report
     * type is under construction is being returned.
     */
    public function generate(array $data): BinaryFileResponse
    {
        $userId = $data['user_id'] ?? null;

        if($userId) {
            $user = User::firstWhere('uuid', $userId);
            $attendances = $user->attendancesByDate((int) $data['year'], (int) $data['month'])->get();

            return Excel::download(
                new AttendanceExport($attendances), 
                "reporte-usuario-" . "{$data['year']}-{$data['month']}-" . date('His') . '.xlsx'
            );
        }

        /** Reporte general de usuario */
        return throw new HttpResponseException(
            response()->json(['message' => "Report type under construction"], 422)
        );
    }   
}